### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ppissanetzky** [larsmagne/usb-automount#2]
Thanks for this - was pulling my hair out too...

Have you considered incorporating the important parts of this into https://github.com/hfuchs/usbmount?

**Comment by larsmagne** [comment]
If the usbmount maintainer wants to incorporate the relevant bits here, it's fine by me, but I'm afraid I don't really have the stamina to fiddle more with udev/systemd than I strictly have to...

**Comment by ppissanetzky** [comment]
I found this [thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774149l) where a similar change is suggested for usbmount and I applied it successfully. Again, many thanks!
